### ISSUE TITLE
Things needed to implement 

### ISSUE THREAD

**Issue by Horryportier** [Horryportier/openup#14]
At this stage this tool is somewhat functional but not **useful**.

## Things that are needed:
- Choose to change dir after opening an folder  
  when opening directory and you exit editor  your are in the same dir as u started this app not in dir of a project. Its an    inconvenience  when u want just to start working some project and you can't use this app. 

for now it's all i really need for this project to be useful but if you have any other you can add them here.

**Comment by nkxxll** [comment]
Well how would you implement that, my first idea is to make an `onExit` Event which gets the last used directory and `cd`s to that directory when you close the app. What are your thoughts on that?

**Comment by Horryportier** [comment]
I think its should be another keybind so if press enter you have the behavior that its right now and if u press `shift+enter` its gonna change to selected dir. Also maybe we can add that when you exit from a file when using only `enter` its dose not exit app

**Comment by Horryportier** [comment]
Another issues:
- no undo button (if u delete something by accident)
- putting all settings with user data was is kinda a bad idea
 if u want to change change json its makes a mess because  all user data are in same file it adds unnecessary complexity separate file would be better.
