### ISSUE TITLE
Changing terminal path is hard!

### ISSUE THREAD

**Issue by Horryportier** [Horryportier/openup#16]
I wanted this app to change my dir in terminal after exiting but i can't find any ease way to do that. 
There is a problem of app being run as new process and making it a troublesome to interact with current session of an terimal.

The easiest  way to do it is to spawn new terminal/tmux session. i think there is a way to do it with some shell script but it would be no convenient. 

If there is any way to do it in code without spawning other terminals it would be the best option. @d1psy-sh If you got any idea it would be helpful.

**Comment by nkxxll** [comment]
## Spawning new sessions

So for the first point there is a nice script from which we can take inspiration, it is called [tmux-sessionizer](https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer) great source for tmux sessions

## ...in the same session

The problem with changing the current working directory in the shell is that the openup program is itself a child process of the current shell session. We would have to find a way to send a command to the parent process (the current shell session) which is a bit difficult but shouldn't be impossible.
I'm going to look into it but aren't shell/tmux sessions the better solution, especially for opening multiple projects? (just wanted to throw that thought in the ring)

**Comment by Horryportier** [comment]
## Sessions
I think i we talk only about tmux `Theprimeagen tmux-sessionizer` is cool direction to go. Also I'm using `kitty term` and I think there's a way to do something similar.

## Same session
I've searched for a while but all i can find is "that it can't be done" or some setting env variable etc nothing with running normal commands. 
But there's maybe something i did not see or understand so if u find a way i will be great.  Its an think that would make this project so much better.

**Comment by nkxxll** [comment]
Didn't find anything for changing the dir in one term session ether...

Yes for kitty there are also terminal tabs like in a tmux session. Don't know whether you are able to make multiple sessions in kitty like in the tmux sessionizer (I'm an old tmux user :smile:).

**Comment by Horryportier** [comment]
Don't know how kitty session exactly work i need to research that :)
