### ISSUE TITLE
Move data.json/config.json to var/lib/openup folder

### ISSUE THREAD

**Issue by Horryportier** [Horryportier/openup#20]
I was researching ways of storing user data for my other project and realized that we just storing data in home dir witch maybe inconvenience for some. From what i read the best place for read-write files is in /var/lib/appname folder.

**Comment by nkxxll** [comment]
Very good :+1:  idea just read the reply on the pr in the inspo repo gonna help where I can but I am kind of stuck in school stuff at the moment have to see whether I find the time... :'(

**Comment by Horryportier** [comment]
No worries there's no time limit to it. Any help is good. :+1:

**Comment by Horryportier** [comment]
It seams i can not put persistent files in /var/lib. So i think i found better place. `.app_name` seams like a good place.
